name: weatherapplication
version: 0.0.1
environment:
  sdk: '>=1.5.0 <2.0.0'
dependencies:
  angular: any
  bootjack: any
  google_maps: any
  web_components: '>=0.8.0 <0.9.0'
  xml: any
transformers:
- angular
